version: '3.8'

networks:
  cisco-api:
    driver: bridge

services:
  api-admin:
    container_name: api_admin
    hostname: api_admin
    image: api_admin:1.0.0
    build:
      context: .
      dockerfile: Admin.Api/Dockerfile
    networks:
      - cisco-api

    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    restart: unless-stopped


#version: '3.4'
#
#services:
#  admin.api:
#    image: ${DOCKER_REGISTRY-}adminapi
#    build:
#      context: .
#      dockerfile: Admin.Api/Dockerfile
