version: '3.8'

services:
  app_admin:
    image: app_admin:latest
    volumes:
      - /usr/local/sncoreapp/https:/app/https
      - /usr/local/sncoreapp/keys:/app/keys
    networks:
      - admin-app-server
      - admin-app
    ports:
      - "8091:8091"
      - "8090:8090"
    environment:
      - ConnectionStrings__Application=Server=${APP_ENV_STR_APPLICATION}
      - ConnectionStrings__Identity=Server=${APP_ENV_STR_IDENTITY}
      - ConnectionStrings__Timescale=Host=${APP_ENV_STR_TIMESCALE}
      - ApiServer__Url=${APP_ENV_HTTPS}
      - ApiServer__WS=${APP_ENV_WS}
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - ASPNETCORE_HTTP_PORTS=8090
      - ASPNETCORE_HTTPS_PORTS=8091
    deploy:
      restart_policy:
        condition: any

networks:
  admin-app-server:
    driver: overlay
  admin-app:
    external: true
