name: Actions SNcore
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build imagem Docker
        run: |
          docker build -t app_admin:latest --target app -f Admin.App/Admin.App/Dockerfile .
