name: Actions SNcore
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name:  Build  Docker image
        run: docker build -t app_admin:latest  --target app -f Admin.App/Admin.App/Dockerfile .